export const USERS_ACCOUNTS = [
    {
      id: "1",
      login: "10009",
      rate: "Floating",
      leverage: "1:500",
      accountType: "Classic Standard (USD)",
      balance: "$5,70",
      equity: "$16,74",
      status: "Active",
    },
    {
      id: "2",
      login: "10014",
      rate: "Fixed",
      leverage: "1:200",
      accountType: "Standard IDR (IDR)",
      balance: "Rp107,000",
      equity: "Rp10,674,000",
      status: "Active",
    },
    {
      id: "3",
      login: "10010",
      rate: "Fixed",
      leverage: "1:100",
      accountType: "Classic Pro (USD)",
      balance: "$500",
      equity: "$1006,74",
      status: "Active",
    },
    {
      id: "4",
      login: "10011",
      rate: "Fixed",
      leverage: "1:200",
      accountType: "Standard IDR (IDR)",
      balance: "Rp107,000",
      equity: "Rp10,674,000",
      status: "Active",
    },
    {
      id: "5",
      login: "10012",
      rate: "Fixed",
      leverage: "1:100",
      accountType: "Classic Pro (USD)",
      balance: "$500",
      equity: "$1006,74",
      status: "Active",
    },
    {
      id: "6",
      login: "10013",
      rate: "Floating",
      leverage: "1:500",
      accountType: "Classic Standard (USD)",
      balance: "$5,70",
      equity: "$16,74",
      status: "Active",
    },
  ]