/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedhomeIndexRouteImport } from './routes/_unauthenticated/(home)/index'
import { Route as UnauthenticatedAboutUsIndexRouteImport } from './routes/_unauthenticated/about-us/index'
import { Route as UnauthenticatedPlatformIndexRouteImport } from './routes/_unauthenticated/platform/index'
import { Route as UnauthenticatedTradingIndexRouteImport } from './routes/_unauthenticated/trading/index'
import { Route as UnauthenticatedauthForgetPasswordIndexRouteImport } from './routes/_unauthenticated/(auth)/forget-password/index'
import { Route as UnauthenticatedauthSignInIndexRouteImport } from './routes/_unauthenticated/(auth)/sign-in/index'
import { Route as UnauthenticatedauthSignUpIndexRouteImport } from './routes/_unauthenticated/(auth)/sign-up/index'

const UnauthenticatedhomeIndexRoute =
  UnauthenticatedhomeIndexRouteImport.update({
    id: '/_unauthenticated/(home)/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedAboutUsIndexRoute =
  UnauthenticatedAboutUsIndexRouteImport.update({
    id: '/_unauthenticated/about-us/',
    path: '/about-us/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedPlatformIndexRoute =
  UnauthenticatedPlatformIndexRouteImport.update({
    id: '/_unauthenticated/platform/',
    path: '/platform/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedTradingIndexRoute =
  UnauthenticatedTradingIndexRouteImport.update({
    id: '/_unauthenticated/trading/',
    path: '/trading/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedauthForgetPasswordIndexRoute =
  UnauthenticatedauthForgetPasswordIndexRouteImport.update({
    id: '/_unauthenticated/(auth)/forget-password/',
    path: '/forget-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedauthSignInIndexRoute =
  UnauthenticatedauthSignInIndexRouteImport.update({
    id: '/_unauthenticated/(auth)/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedauthSignUpIndexRoute =
  UnauthenticatedauthSignUpIndexRouteImport.update({
    id: '/_unauthenticated/(auth)/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthenticatedhomeIndexRoute
  '/about-us/': typeof UnauthenticatedAboutUsIndexRoute
  '/platform/': typeof UnauthenticatedPlatformIndexRoute
  '/trading/': typeof UnauthenticatedTradingIndexRoute
  '/forget-password/': typeof UnauthenticatedauthForgetPasswordIndexRoute
  '/sign-in/': typeof UnauthenticatedauthSignInIndexRoute
  '/sign-up/': typeof UnauthenticatedauthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof UnauthenticatedhomeIndexRoute
  '/about-us': typeof UnauthenticatedAboutUsIndexRoute
  '/platform': typeof UnauthenticatedPlatformIndexRoute
  '/trading': typeof UnauthenticatedTradingIndexRoute
  '/forget-password': typeof UnauthenticatedauthForgetPasswordIndexRoute
  '/sign-in': typeof UnauthenticatedauthSignInIndexRoute
  '/sign-up': typeof UnauthenticatedauthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_unauthenticated/(home)/': typeof UnauthenticatedhomeIndexRoute
  '/_unauthenticated/about-us/': typeof UnauthenticatedAboutUsIndexRoute
  '/_unauthenticated/platform/': typeof UnauthenticatedPlatformIndexRoute
  '/_unauthenticated/trading/': typeof UnauthenticatedTradingIndexRoute
  '/_unauthenticated/(auth)/forget-password/': typeof UnauthenticatedauthForgetPasswordIndexRoute
  '/_unauthenticated/(auth)/sign-in/': typeof UnauthenticatedauthSignInIndexRoute
  '/_unauthenticated/(auth)/sign-up/': typeof UnauthenticatedauthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us/'
    | '/platform/'
    | '/trading/'
    | '/forget-password/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/platform'
    | '/trading'
    | '/forget-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/_unauthenticated/(home)/'
    | '/_unauthenticated/about-us/'
    | '/_unauthenticated/platform/'
    | '/_unauthenticated/trading/'
    | '/_unauthenticated/(auth)/forget-password/'
    | '/_unauthenticated/(auth)/sign-in/'
    | '/_unauthenticated/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UnauthenticatedhomeIndexRoute: typeof UnauthenticatedhomeIndexRoute
  UnauthenticatedAboutUsIndexRoute: typeof UnauthenticatedAboutUsIndexRoute
  UnauthenticatedPlatformIndexRoute: typeof UnauthenticatedPlatformIndexRoute
  UnauthenticatedTradingIndexRoute: typeof UnauthenticatedTradingIndexRoute
  UnauthenticatedauthForgetPasswordIndexRoute: typeof UnauthenticatedauthForgetPasswordIndexRoute
  UnauthenticatedauthSignInIndexRoute: typeof UnauthenticatedauthSignInIndexRoute
  UnauthenticatedauthSignUpIndexRoute: typeof UnauthenticatedauthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated/(home)/': {
      id: '/_unauthenticated/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedhomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/about-us/': {
      id: '/_unauthenticated/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof UnauthenticatedAboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/platform/': {
      id: '/_unauthenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof UnauthenticatedPlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/trading/': {
      id: '/_unauthenticated/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof UnauthenticatedTradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/(auth)/forget-password/': {
      id: '/_unauthenticated/(auth)/forget-password/'
      path: '/forget-password'
      fullPath: '/forget-password/'
      preLoaderRoute: typeof UnauthenticatedauthForgetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/(auth)/sign-in/': {
      id: '/_unauthenticated/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof UnauthenticatedauthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/(auth)/sign-up/': {
      id: '/_unauthenticated/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof UnauthenticatedauthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  UnauthenticatedhomeIndexRoute: UnauthenticatedhomeIndexRoute,
  UnauthenticatedAboutUsIndexRoute: UnauthenticatedAboutUsIndexRoute,
  UnauthenticatedPlatformIndexRoute: UnauthenticatedPlatformIndexRoute,
  UnauthenticatedTradingIndexRoute: UnauthenticatedTradingIndexRoute,
  UnauthenticatedauthForgetPasswordIndexRoute:
    UnauthenticatedauthForgetPasswordIndexRoute,
  UnauthenticatedauthSignInIndexRoute: UnauthenticatedauthSignInIndexRoute,
  UnauthenticatedauthSignUpIndexRoute: UnauthenticatedauthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
