/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as TradingIndexRouteImport } from './routes/trading/index'
import { Route as authForgetPasswordIndexRouteImport } from './routes/(auth)/forget-password/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordIndexRoute = authForgetPasswordIndexRouteImport.update({
  id: '/(auth)/forget-password/',
  path: '/forget-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trading/': typeof TradingIndexRoute
  '/forget-password/': typeof authForgetPasswordIndexRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/trading': typeof TradingIndexRoute
  '/forget-password': typeof authForgetPasswordIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trading/': typeof TradingIndexRoute
  '/(auth)/forget-password/': typeof authForgetPasswordIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us/'
    | '/platform/'
    | '/trading/'
    | '/forget-password/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/platform'
    | '/trading'
    | '/forget-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(home)/'
    | '/about-us/'
    | '/platform/'
    | '/trading/'
    | '/(auth)/forget-password/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
  authForgetPasswordIndexRoute: typeof authForgetPasswordIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password/': {
      id: '/(auth)/forget-password/'
      path: '/forget-password'
      fullPath: '/forget-password/'
      preLoaderRoute: typeof authForgetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
  authForgetPasswordIndexRoute: authForgetPasswordIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
